# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

abbr --add kg "k get"
abbr --add kt "k tree"
abbr --add kd "k describe"
abbr --add ka "k apply -f"
abbr --add kx "k exec -i -t"
abbr --add kl "k logs -f"
abbr --add krm "k delete"
abbr --add krr "k rollout restart"
abbr --add krun "k run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add kgpo "k get pods"
abbr --add kdpo "k describe pods"
abbr --add krmpo "k delete pods"
abbr --add kgdep "k get deployment"
abbr --add ktdep "k tree deployment"
abbr --add kddep "k describe deployment"
abbr --add krmdep "k delete deployment"
abbr --add krrdep "k rollout restart deployment"
abbr --add kgsts "k get statefulset"
abbr --add ktsts "k tree statefulset"
abbr --add kdsts "k describe statefulset"
abbr --add krmsts "k delete statefulset"
abbr --add krrsts "k rollout restart statefulset"
abbr --add kgsvc "k get service"
abbr --add kdsvc "k describe service"
abbr --add krmsvc "k delete service"
abbr --add kging "k get ingress"
abbr --add kding "k describe ingress"
abbr --add krming "k delete ingress"
abbr --add kgcm "k get configmap"
abbr --add kdcm "k describe configmap"
abbr --add krmcm "k delete configmap"
abbr --add kgsec "k get secret"
abbr --add kdsec "k describe secret"
abbr --add krmsec "k delete secret"
abbr --add kgno "k get nodes"
abbr --add kdno "k describe nodes"
abbr --add kgns "k get namespaces"
abbr --add kdns "k describe namespaces"
abbr --add krmns "k delete namespaces"
abbr --add kgowide "k get -o=wide"
abbr --add kgpoowide "k get pods -o=wide"
abbr --add kgdepowide "k get deployment -o=wide"
abbr --add kgstsowide "k get statefulset -o=wide"
abbr --add kgsvcowide "k get service -o=wide"
abbr --add kgingowide "k get ingress -o=wide"
abbr --add kgcmowide "k get configmap -o=wide"
abbr --add kgsecowide "k get secret -o=wide"
abbr --add kgnoowide "k get nodes -o=wide"
abbr --add kgnsowide "k get namespaces -o=wide"
abbr --add kgoyaml "k get -o=yaml"
abbr --add kgpooyaml "k get pods -o=yaml"
abbr --add kgdepoyaml "k get deployment -o=yaml"
abbr --add kgstsoyaml "k get statefulset -o=yaml"
abbr --add kgsvcoyaml "k get service -o=yaml"
abbr --add kgingoyaml "k get ingress -o=yaml"
abbr --add kgcmoyaml "k get configmap -o=yaml"
abbr --add kgsecoyaml "k get secret -o=yaml"
abbr --add kgnooyaml "k get nodes -o=yaml"
abbr --add kgnsoyaml "k get namespaces -o=yaml"
abbr --add kgojson "k get -o=json"
abbr --add kgpoojson "k get pods -o=json"
abbr --add kgdepojson "k get deployment -o=json"
abbr --add kgstsojson "k get statefulset -o=json"
abbr --add kgsvcojson "k get service -o=json"
abbr --add kgingojson "k get ingress -o=json"
abbr --add kgcmojson "k get configmap -o=json"
abbr --add kgsecojson "k get secret -o=json"
abbr --add kgnoojson "k get nodes -o=json"
abbr --add kgnsojson "k get namespaces -o=json"
abbr --add kgall "k get --all-namespaces"
abbr --add kdall "k describe --all-namespaces"
abbr --add kgpoall "k get pods --all-namespaces"
abbr --add kdpoall "k describe pods --all-namespaces"
abbr --add kgdepall "k get deployment --all-namespaces"
abbr --add kddepall "k describe deployment --all-namespaces"
abbr --add kgstsall "k get statefulset --all-namespaces"
abbr --add kdstsall "k describe statefulset --all-namespaces"
abbr --add kgsvcall "k get service --all-namespaces"
abbr --add kdsvcall "k describe service --all-namespaces"
abbr --add kgingall "k get ingress --all-namespaces"
abbr --add kdingall "k describe ingress --all-namespaces"
abbr --add kgcmall "k get configmap --all-namespaces"
abbr --add kdcmall "k describe configmap --all-namespaces"
abbr --add kgsecall "k get secret --all-namespaces"
abbr --add kdsecall "k describe secret --all-namespaces"
abbr --add kgsl "k get --show-labels"
abbr --add kgposl "k get pods --show-labels"
abbr --add kgdepsl "k get deployment --show-labels"
abbr --add kgstssl "k get statefulset --show-labels"
abbr --add kgsvcsl "k get service --show-labels"
abbr --add kgingsl "k get ingress --show-labels"
abbr --add kgcmsl "k get configmap --show-labels"
abbr --add kgsecsl "k get secret --show-labels"
abbr --add kgnosl "k get nodes --show-labels"
abbr --add kgnssl "k get namespaces --show-labels"
abbr --add kgw "k get --watch"
abbr --add kgpow "k get pods --watch"
abbr --add kgdepw "k get deployment --watch"
abbr --add kgstsw "k get statefulset --watch"
abbr --add kgsvcw "k get service --watch"
abbr --add kgingw "k get ingress --watch"
abbr --add kgcmw "k get configmap --watch"
abbr --add kgsecw "k get secret --watch"
abbr --add kgnow "k get nodes --watch"
abbr --add kgnsw "k get namespaces --watch"
abbr --add kgowideall "k get -o=wide --all-namespaces"
abbr --add kgpoowideall "k get pods -o=wide --all-namespaces"
abbr --add kgdepowideall "k get deployment -o=wide --all-namespaces"
abbr --add kgstsowideall "k get statefulset -o=wide --all-namespaces"
abbr --add kgsvcowideall "k get service -o=wide --all-namespaces"
abbr --add kgingowideall "k get ingress -o=wide --all-namespaces"
abbr --add kgcmowideall "k get configmap -o=wide --all-namespaces"
abbr --add kgsecowideall "k get secret -o=wide --all-namespaces"
abbr --add kgallowide "k get --all-namespaces -o=wide"
abbr --add kgpoallowide "k get pods --all-namespaces -o=wide"
abbr --add kgdepallowide "k get deployment --all-namespaces -o=wide"
abbr --add kgstsallowide "k get statefulset --all-namespaces -o=wide"
abbr --add kgsvcallowide "k get service --all-namespaces -o=wide"
abbr --add kgingallowide "k get ingress --all-namespaces -o=wide"
abbr --add kgcmallowide "k get configmap --all-namespaces -o=wide"
abbr --add kgsecallowide "k get secret --all-namespaces -o=wide"
abbr --add kgowidesl "k get -o=wide --show-labels"
abbr --add kgpoowidesl "k get pods -o=wide --show-labels"
abbr --add kgdepowidesl "k get deployment -o=wide --show-labels"
abbr --add kgstsowidesl "k get statefulset -o=wide --show-labels"
abbr --add kgsvcowidesl "k get service -o=wide --show-labels"
abbr --add kgingowidesl "k get ingress -o=wide --show-labels"
abbr --add kgcmowidesl "k get configmap -o=wide --show-labels"
abbr --add kgsecowidesl "k get secret -o=wide --show-labels"
abbr --add kgnoowidesl "k get nodes -o=wide --show-labels"
abbr --add kgnsowidesl "k get namespaces -o=wide --show-labels"
abbr --add kgslowide "k get --show-labels -o=wide"
abbr --add kgposlowide "k get pods --show-labels -o=wide"
abbr --add kgdepslowide "k get deployment --show-labels -o=wide"
abbr --add kgstsslowide "k get statefulset --show-labels -o=wide"
abbr --add kgsvcslowide "k get service --show-labels -o=wide"
abbr --add kgingslowide "k get ingress --show-labels -o=wide"
abbr --add kgcmslowide "k get configmap --show-labels -o=wide"
abbr --add kgsecslowide "k get secret --show-labels -o=wide"
abbr --add kgnoslowide "k get nodes --show-labels -o=wide"
abbr --add kgnsslowide "k get namespaces --show-labels -o=wide"
abbr --add kgoyamlall "k get -o=yaml --all-namespaces"
abbr --add kgpooyamlall "k get pods -o=yaml --all-namespaces"
abbr --add kgdepoyamlall "k get deployment -o=yaml --all-namespaces"
abbr --add kgstsoyamlall "k get statefulset -o=yaml --all-namespaces"
abbr --add kgsvcoyamlall "k get service -o=yaml --all-namespaces"
abbr --add kgingoyamlall "k get ingress -o=yaml --all-namespaces"
abbr --add kgcmoyamlall "k get configmap -o=yaml --all-namespaces"
abbr --add kgsecoyamlall "k get secret -o=yaml --all-namespaces"
abbr --add kgalloyaml "k get --all-namespaces -o=yaml"
abbr --add kgpoalloyaml "k get pods --all-namespaces -o=yaml"
abbr --add kgdepalloyaml "k get deployment --all-namespaces -o=yaml"
abbr --add kgstsalloyaml "k get statefulset --all-namespaces -o=yaml"
abbr --add kgsvcalloyaml "k get service --all-namespaces -o=yaml"
abbr --add kgingalloyaml "k get ingress --all-namespaces -o=yaml"
abbr --add kgcmalloyaml "k get configmap --all-namespaces -o=yaml"
abbr --add kgsecalloyaml "k get secret --all-namespaces -o=yaml"
abbr --add kgojsonall "k get -o=json --all-namespaces"
abbr --add kgpoojsonall "k get pods -o=json --all-namespaces"
abbr --add kgdepojsonall "k get deployment -o=json --all-namespaces"
abbr --add kgstsojsonall "k get statefulset -o=json --all-namespaces"
abbr --add kgsvcojsonall "k get service -o=json --all-namespaces"
abbr --add kgingojsonall "k get ingress -o=json --all-namespaces"
abbr --add kgcmojsonall "k get configmap -o=json --all-namespaces"
abbr --add kgsecojsonall "k get secret -o=json --all-namespaces"
abbr --add kgallojson "k get --all-namespaces -o=json"
abbr --add kgpoallojson "k get pods --all-namespaces -o=json"
abbr --add kgdepallojson "k get deployment --all-namespaces -o=json"
abbr --add kgstsallojson "k get statefulset --all-namespaces -o=json"
abbr --add kgsvcallojson "k get service --all-namespaces -o=json"
abbr --add kgingallojson "k get ingress --all-namespaces -o=json"
abbr --add kgcmallojson "k get configmap --all-namespaces -o=json"
abbr --add kgsecallojson "k get secret --all-namespaces -o=json"
abbr --add kgallsl "k get --all-namespaces --show-labels"
abbr --add kgpoallsl "k get pods --all-namespaces --show-labels"
abbr --add kgdepallsl "k get deployment --all-namespaces --show-labels"
abbr --add kgstsallsl "k get statefulset --all-namespaces --show-labels"
abbr --add kgsvcallsl "k get service --all-namespaces --show-labels"
abbr --add kgingallsl "k get ingress --all-namespaces --show-labels"
abbr --add kgcmallsl "k get configmap --all-namespaces --show-labels"
abbr --add kgsecallsl "k get secret --all-namespaces --show-labels"
abbr --add kgslall "k get --show-labels --all-namespaces"
abbr --add kgposlall "k get pods --show-labels --all-namespaces"
abbr --add kgdepslall "k get deployment --show-labels --all-namespaces"
abbr --add kgstsslall "k get statefulset --show-labels --all-namespaces"
abbr --add kgsvcslall "k get service --show-labels --all-namespaces"
abbr --add kgingslall "k get ingress --show-labels --all-namespaces"
abbr --add kgcmslall "k get configmap --show-labels --all-namespaces"
abbr --add kgsecslall "k get secret --show-labels --all-namespaces"
abbr --add kgallw "k get --all-namespaces --watch"
abbr --add kgpoallw "k get pods --all-namespaces --watch"
abbr --add kgdepallw "k get deployment --all-namespaces --watch"
abbr --add kgstsallw "k get statefulset --all-namespaces --watch"
abbr --add kgsvcallw "k get service --all-namespaces --watch"
abbr --add kgingallw "k get ingress --all-namespaces --watch"
abbr --add kgcmallw "k get configmap --all-namespaces --watch"
abbr --add kgsecallw "k get secret --all-namespaces --watch"
abbr --add kgwall "k get --watch --all-namespaces"
abbr --add kgpowall "k get pods --watch --all-namespaces"
abbr --add kgdepwall "k get deployment --watch --all-namespaces"
abbr --add kgstswall "k get statefulset --watch --all-namespaces"
abbr --add kgsvcwall "k get service --watch --all-namespaces"
abbr --add kgingwall "k get ingress --watch --all-namespaces"
abbr --add kgcmwall "k get configmap --watch --all-namespaces"
abbr --add kgsecwall "k get secret --watch --all-namespaces"
abbr --add kgslw "k get --show-labels --watch"
abbr --add kgposlw "k get pods --show-labels --watch"
abbr --add kgdepslw "k get deployment --show-labels --watch"
abbr --add kgstsslw "k get statefulset --show-labels --watch"
abbr --add kgsvcslw "k get service --show-labels --watch"
abbr --add kgingslw "k get ingress --show-labels --watch"
abbr --add kgcmslw "k get configmap --show-labels --watch"
abbr --add kgsecslw "k get secret --show-labels --watch"
abbr --add kgnoslw "k get nodes --show-labels --watch"
abbr --add kgnsslw "k get namespaces --show-labels --watch"
abbr --add kgwsl "k get --watch --show-labels"
abbr --add kgpowsl "k get pods --watch --show-labels"
abbr --add kgdepwsl "k get deployment --watch --show-labels"
abbr --add kgstswsl "k get statefulset --watch --show-labels"
abbr --add kgsvcwsl "k get service --watch --show-labels"
abbr --add kgingwsl "k get ingress --watch --show-labels"
abbr --add kgcmwsl "k get configmap --watch --show-labels"
abbr --add kgsecwsl "k get secret --watch --show-labels"
abbr --add kgnowsl "k get nodes --watch --show-labels"
abbr --add kgnswsl "k get namespaces --watch --show-labels"
abbr --add kgowideallsl "k get -o=wide --all-namespaces --show-labels"
abbr --add kgpoowideallsl "k get pods -o=wide --all-namespaces --show-labels"
abbr --add kgdepowideallsl "k get deployment -o=wide --all-namespaces --show-labels"
abbr --add kgstsowideallsl "k get statefulset -o=wide --all-namespaces --show-labels"
abbr --add kgsvcowideallsl "k get service -o=wide --all-namespaces --show-labels"
abbr --add kgingowideallsl "k get ingress -o=wide --all-namespaces --show-labels"
abbr --add kgcmowideallsl "k get configmap -o=wide --all-namespaces --show-labels"
abbr --add kgsecowideallsl "k get secret -o=wide --all-namespaces --show-labels"
abbr --add kgowideslall "k get -o=wide --show-labels --all-namespaces"
abbr --add kgpoowideslall "k get pods -o=wide --show-labels --all-namespaces"
abbr --add kgdepowideslall "k get deployment -o=wide --show-labels --all-namespaces"
abbr --add kgstsowideslall "k get statefulset -o=wide --show-labels --all-namespaces"
abbr --add kgsvcowideslall "k get service -o=wide --show-labels --all-namespaces"
abbr --add kgingowideslall "k get ingress -o=wide --show-labels --all-namespaces"
abbr --add kgcmowideslall "k get configmap -o=wide --show-labels --all-namespaces"
abbr --add kgsecowideslall "k get secret -o=wide --show-labels --all-namespaces"
abbr --add kgallowidesl "k get --all-namespaces -o=wide --show-labels"
abbr --add kgpoallowidesl "k get pods --all-namespaces -o=wide --show-labels"
abbr --add kgdepallowidesl "k get deployment --all-namespaces -o=wide --show-labels"
abbr --add kgstsallowidesl "k get statefulset --all-namespaces -o=wide --show-labels"
abbr --add kgsvcallowidesl "k get service --all-namespaces -o=wide --show-labels"
abbr --add kgingallowidesl "k get ingress --all-namespaces -o=wide --show-labels"
abbr --add kgcmallowidesl "k get configmap --all-namespaces -o=wide --show-labels"
abbr --add kgsecallowidesl "k get secret --all-namespaces -o=wide --show-labels"
abbr --add kgallslowide "k get --all-namespaces --show-labels -o=wide"
abbr --add kgpoallslowide "k get pods --all-namespaces --show-labels -o=wide"
abbr --add kgdepallslowide "k get deployment --all-namespaces --show-labels -o=wide"
abbr --add kgstsallslowide "k get statefulset --all-namespaces --show-labels -o=wide"
abbr --add kgsvcallslowide "k get service --all-namespaces --show-labels -o=wide"
abbr --add kgingallslowide "k get ingress --all-namespaces --show-labels -o=wide"
abbr --add kgcmallslowide "k get configmap --all-namespaces --show-labels -o=wide"
abbr --add kgsecallslowide "k get secret --all-namespaces --show-labels -o=wide"
abbr --add kgslowideall "k get --show-labels -o=wide --all-namespaces"
abbr --add kgposlowideall "k get pods --show-labels -o=wide --all-namespaces"
abbr --add kgdepslowideall "k get deployment --show-labels -o=wide --all-namespaces"
abbr --add kgstsslowideall "k get statefulset --show-labels -o=wide --all-namespaces"
abbr --add kgsvcslowideall "k get service --show-labels -o=wide --all-namespaces"
abbr --add kgingslowideall "k get ingress --show-labels -o=wide --all-namespaces"
abbr --add kgcmslowideall "k get configmap --show-labels -o=wide --all-namespaces"
abbr --add kgsecslowideall "k get secret --show-labels -o=wide --all-namespaces"
abbr --add kgslallowide "k get --show-labels --all-namespaces -o=wide"
abbr --add kgposlallowide "k get pods --show-labels --all-namespaces -o=wide"
abbr --add kgdepslallowide "k get deployment --show-labels --all-namespaces -o=wide"
abbr --add kgstsslallowide "k get statefulset --show-labels --all-namespaces -o=wide"
abbr --add kgsvcslallowide "k get service --show-labels --all-namespaces -o=wide"
abbr --add kgingslallowide "k get ingress --show-labels --all-namespaces -o=wide"
abbr --add kgcmslallowide "k get configmap --show-labels --all-namespaces -o=wide"
abbr --add kgsecslallowide "k get secret --show-labels --all-namespaces -o=wide"
abbr --add kgallslw "k get --all-namespaces --show-labels --watch"
abbr --add kgpoallslw "k get pods --all-namespaces --show-labels --watch"
abbr --add kgdepallslw "k get deployment --all-namespaces --show-labels --watch"
abbr --add kgstsallslw "k get statefulset --all-namespaces --show-labels --watch"
abbr --add kgsvcallslw "k get service --all-namespaces --show-labels --watch"
abbr --add kgingallslw "k get ingress --all-namespaces --show-labels --watch"
abbr --add kgcmallslw "k get configmap --all-namespaces --show-labels --watch"
abbr --add kgsecallslw "k get secret --all-namespaces --show-labels --watch"
abbr --add kgallwsl "k get --all-namespaces --watch --show-labels"
abbr --add kgpoallwsl "k get pods --all-namespaces --watch --show-labels"
abbr --add kgdepallwsl "k get deployment --all-namespaces --watch --show-labels"
abbr --add kgstsallwsl "k get statefulset --all-namespaces --watch --show-labels"
abbr --add kgsvcallwsl "k get service --all-namespaces --watch --show-labels"
abbr --add kgingallwsl "k get ingress --all-namespaces --watch --show-labels"
abbr --add kgcmallwsl "k get configmap --all-namespaces --watch --show-labels"
abbr --add kgsecallwsl "k get secret --all-namespaces --watch --show-labels"
abbr --add kgslallw "k get --show-labels --all-namespaces --watch"
abbr --add kgposlallw "k get pods --show-labels --all-namespaces --watch"
abbr --add kgdepslallw "k get deployment --show-labels --all-namespaces --watch"
abbr --add kgstsslallw "k get statefulset --show-labels --all-namespaces --watch"
abbr --add kgsvcslallw "k get service --show-labels --all-namespaces --watch"
abbr --add kgingslallw "k get ingress --show-labels --all-namespaces --watch"
abbr --add kgcmslallw "k get configmap --show-labels --all-namespaces --watch"
abbr --add kgsecslallw "k get secret --show-labels --all-namespaces --watch"
abbr --add kgslwall "k get --show-labels --watch --all-namespaces"
abbr --add kgposlwall "k get pods --show-labels --watch --all-namespaces"
abbr --add kgdepslwall "k get deployment --show-labels --watch --all-namespaces"
abbr --add kgstsslwall "k get statefulset --show-labels --watch --all-namespaces"
abbr --add kgsvcslwall "k get service --show-labels --watch --all-namespaces"
abbr --add kgingslwall "k get ingress --show-labels --watch --all-namespaces"
abbr --add kgcmslwall "k get configmap --show-labels --watch --all-namespaces"
abbr --add kgsecslwall "k get secret --show-labels --watch --all-namespaces"
abbr --add kgwallsl "k get --watch --all-namespaces --show-labels"
abbr --add kgpowallsl "k get pods --watch --all-namespaces --show-labels"
abbr --add kgdepwallsl "k get deployment --watch --all-namespaces --show-labels"
abbr --add kgstswallsl "k get statefulset --watch --all-namespaces --show-labels"
abbr --add kgsvcwallsl "k get service --watch --all-namespaces --show-labels"
abbr --add kgingwallsl "k get ingress --watch --all-namespaces --show-labels"
abbr --add kgcmwallsl "k get configmap --watch --all-namespaces --show-labels"
abbr --add kgsecwallsl "k get secret --watch --all-namespaces --show-labels"
abbr --add kgwslall "k get --watch --show-labels --all-namespaces"
abbr --add kgpowslall "k get pods --watch --show-labels --all-namespaces"
abbr --add kgdepwslall "k get deployment --watch --show-labels --all-namespaces"
abbr --add kgstswslall "k get statefulset --watch --show-labels --all-namespaces"
abbr --add kgsvcwslall "k get service --watch --show-labels --all-namespaces"
abbr --add kgingwslall "k get ingress --watch --show-labels --all-namespaces"
abbr --add kgcmwslall "k get configmap --watch --show-labels --all-namespaces"
abbr --add kgsecwslall "k get secret --watch --show-labels --all-namespaces"
abbr --add kgn "k get --namespace"
abbr --add ktn "k tree --namespace"
abbr --add kdn "k describe --namespace"
abbr --add kxn "k exec -i -t --namespace"
abbr --add kln "k logs -f --namespace"
abbr --add krmn "k delete --namespace"
abbr --add kgpon "k get pods --namespace"
abbr --add kdpon "k describe pods --namespace"
abbr --add krmpon "k delete pods --namespace"
abbr --add kgdepn "k get deployment --namespace"
abbr --add ktdepn "k tree deployment --namespace"
abbr --add kddepn "k describe deployment --namespace"
abbr --add krmdepn "k delete deployment --namespace"
abbr --add kgstsn "k get statefulset --namespace"
abbr --add ktstsn "k tree statefulset --namespace"
abbr --add kdstsn "k describe statefulset --namespace"
abbr --add krmstsn "k delete statefulset --namespace"
abbr --add kgsvcn "k get service --namespace"
abbr --add kdsvcn "k describe service --namespace"
abbr --add krmsvcn "k delete service --namespace"
abbr --add kgingn "k get ingress --namespace"
abbr --add kdingn "k describe ingress --namespace"
abbr --add krmingn "k delete ingress --namespace"
abbr --add kgcmn "k get configmap --namespace"
abbr --add kdcmn "k describe configmap --namespace"
abbr --add krmcmn "k delete configmap --namespace"
abbr --add kgsecn "k get secret --namespace"
abbr --add kdsecn "k describe secret --namespace"
abbr --add krmsecn "k delete secret --namespace"
abbr --add kgowiden "k get -o=wide --namespace"
abbr --add kgpoowiden "k get pods -o=wide --namespace"
abbr --add kgdepowiden "k get deployment -o=wide --namespace"
abbr --add kgstsowiden "k get statefulset -o=wide --namespace"
abbr --add kgsvcowiden "k get service -o=wide --namespace"
abbr --add kgingowiden "k get ingress -o=wide --namespace"
abbr --add kgcmowiden "k get configmap -o=wide --namespace"
abbr --add kgsecowiden "k get secret -o=wide --namespace"
abbr --add kgoyamln "k get -o=yaml --namespace"
abbr --add kgpooyamln "k get pods -o=yaml --namespace"
abbr --add kgdepoyamln "k get deployment -o=yaml --namespace"
abbr --add kgstsoyamln "k get statefulset -o=yaml --namespace"
abbr --add kgsvcoyamln "k get service -o=yaml --namespace"
abbr --add kgingoyamln "k get ingress -o=yaml --namespace"
abbr --add kgcmoyamln "k get configmap -o=yaml --namespace"
abbr --add kgsecoyamln "k get secret -o=yaml --namespace"
abbr --add kgojsonn "k get -o=json --namespace"
abbr --add kgpoojsonn "k get pods -o=json --namespace"
abbr --add kgdepojsonn "k get deployment -o=json --namespace"
abbr --add kgstsojsonn "k get statefulset -o=json --namespace"
abbr --add kgsvcojsonn "k get service -o=json --namespace"
abbr --add kgingojsonn "k get ingress -o=json --namespace"
abbr --add kgcmojsonn "k get configmap -o=json --namespace"
abbr --add kgsecojsonn "k get secret -o=json --namespace"
abbr --add kgsln "k get --show-labels --namespace"
abbr --add kgposln "k get pods --show-labels --namespace"
abbr --add kgdepsln "k get deployment --show-labels --namespace"
abbr --add kgstssln "k get statefulset --show-labels --namespace"
abbr --add kgsvcsln "k get service --show-labels --namespace"
abbr --add kgingsln "k get ingress --show-labels --namespace"
abbr --add kgcmsln "k get configmap --show-labels --namespace"
abbr --add kgsecsln "k get secret --show-labels --namespace"
abbr --add kgwn "k get --watch --namespace"
abbr --add kgpown "k get pods --watch --namespace"
abbr --add kgdepwn "k get deployment --watch --namespace"
abbr --add kgstswn "k get statefulset --watch --namespace"
abbr --add kgsvcwn "k get service --watch --namespace"
abbr --add kgingwn "k get ingress --watch --namespace"
abbr --add kgcmwn "k get configmap --watch --namespace"
abbr --add kgsecwn "k get secret --watch --namespace"
abbr --add kgowidesln "k get -o=wide --show-labels --namespace"
abbr --add kgpoowidesln "k get pods -o=wide --show-labels --namespace"
abbr --add kgdepowidesln "k get deployment -o=wide --show-labels --namespace"
abbr --add kgstsowidesln "k get statefulset -o=wide --show-labels --namespace"
abbr --add kgsvcowidesln "k get service -o=wide --show-labels --namespace"
abbr --add kgingowidesln "k get ingress -o=wide --show-labels --namespace"
abbr --add kgcmowidesln "k get configmap -o=wide --show-labels --namespace"
abbr --add kgsecowidesln "k get secret -o=wide --show-labels --namespace"
abbr --add kgslowiden "k get --show-labels -o=wide --namespace"
abbr --add kgposlowiden "k get pods --show-labels -o=wide --namespace"
abbr --add kgdepslowiden "k get deployment --show-labels -o=wide --namespace"
abbr --add kgstsslowiden "k get statefulset --show-labels -o=wide --namespace"
abbr --add kgsvcslowiden "k get service --show-labels -o=wide --namespace"
abbr --add kgingslowiden "k get ingress --show-labels -o=wide --namespace"
abbr --add kgcmslowiden "k get configmap --show-labels -o=wide --namespace"
abbr --add kgsecslowiden "k get secret --show-labels -o=wide --namespace"
abbr --add kgslwn "k get --show-labels --watch --namespace"
abbr --add kgposlwn "k get pods --show-labels --watch --namespace"
abbr --add kgdepslwn "k get deployment --show-labels --watch --namespace"
abbr --add kgstsslwn "k get statefulset --show-labels --watch --namespace"
abbr --add kgsvcslwn "k get service --show-labels --watch --namespace"
abbr --add kgingslwn "k get ingress --show-labels --watch --namespace"
abbr --add kgcmslwn "k get configmap --show-labels --watch --namespace"
abbr --add kgsecslwn "k get secret --show-labels --watch --namespace"
abbr --add kgwsln "k get --watch --show-labels --namespace"
abbr --add kgpowsln "k get pods --watch --show-labels --namespace"
abbr --add kgdepwsln "k get deployment --watch --show-labels --namespace"
abbr --add kgstswsln "k get statefulset --watch --show-labels --namespace"
abbr --add kgsvcwsln "k get service --watch --show-labels --namespace"
abbr --add kgingwsln "k get ingress --watch --show-labels --namespace"
abbr --add kgcmwsln "k get configmap --watch --show-labels --namespace"
abbr --add kgsecwsln "k get secret --watch --show-labels --namespace"
